import Link from "next/link";
import { notFound } from "next/navigation";
import { requireOrganization } from "@/lib/auth/dal";
import { createClient } from "@/lib/supabase/server";
import { valuationResponseSchema, valuationInputSchema, featureLabels, propertyTypes } from "@/lib/valuations/somantic";
import { PrintReportButton } from "@/components/valuations/print-report-button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const euro=new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR",maximumFractionDigits:0});
const amount=(value:number|null|undefined)=>value==null ? "Keine belastbare Schätzung" : euro.format(value);
const quality={high:"Hoch",medium:"Mittel",low:"Niedrig",none:"Nicht ausreichend"};
export default async function ValuationReportPage({params}:{params:Promise<{id:string}>}){
  const {id}=await params; const viewer=await requireOrganization();const supabase=await createClient();
  const {data:report}=await supabase.from("somantic_valuation_reports").select("*").eq("id",id).eq("organization_id",viewer.organizationId).maybeSingle();if(!report)notFound();
  const {data:property}=await supabase.from("properties").select("name").eq("id",report.property_id).eq("organization_id",viewer.organizationId).maybeSingle();
  const result=valuationResponseSchema.safeParse(report.response);const input=valuationInputSchema.safeParse(report.input);
  return <article className="mx-auto max-w-5xl space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><Link href="/app/markt" className="text-sm underline print:hidden">Zurück zu Bewertungen</Link><PrintReportButton/></div>
    <header><p className="text-sm text-muted-foreground">EstateBrain · Somantic · {report.valuation_year}</p><h1 className="text-3xl font-semibold">Bewertungsbericht: {property?.name ?? "Immobilie"}</h1><p className="mt-2 text-muted-foreground">Stand: {new Date(report.requested_at).toLocaleDateString("de-DE",{timeZone:"Europe/Berlin"})} · Modellbasierte Marktwerteinschätzung</p></header>
    {report.error_message && <p role="alert">{report.error_message}</p>}
    {result.success ? <><div className="grid gap-4 sm:grid-cols-2">{([ ["Kaufpreis",result.data.estimates.price,result.data.estimates.price_range,result.data.confidence.price], ["Kaltmiete pro Monat",result.data.estimates.rent,result.data.estimates.rent_range,result.data.confidence.rent] ] as const).map(([title,value,range,confidence])=><Card key={title}><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent><p className="text-3xl font-semibold">{amount(value)}</p>{range && <p className="mt-2">Spanne: {amount(range.low)} – {amount(range.high)}</p>}<p className="mt-2 text-sm text-muted-foreground">Datenqualität: {quality[confidence]}</p></CardContent></Card>)}</div>
      {(result.data.estimates.price==null || result.data.estimates.rent==null) && <p className="rounded-lg bg-amber-50 p-4 text-amber-900">Für mindestens einen Wert liegen zu wenige Vergleichsobjekte vor. Fehlende Werte werden nicht als Null gebucht; ein vorhandener Marktwert bleibt erhalten.</p>}
      <Card><CardHeader><CardTitle>Datengrundlage</CardTitle></CardHeader><CardContent className="space-y-2"><p>{result.data.confidence.sample_size} bereinigte Vergleichsobjekte insgesamt · Kauf: {result.data.estimates.price_per_square_meter?.count ?? "–"} · Miete: {result.data.estimates.rent_per_square_meter?.count ?? "–"}</p><p>Mittlerer Kaufpreis je m²: {amount(result.data.estimates.price_per_square_meter?.mean)} · Kaltmiete je m²: {amount(result.data.estimates.rent_per_square_meter?.mean)}</p><p>Aktualitätsfenster: {result.data.confidence.recency_window_months ? `${result.data.confidence.recency_window_months} Monate` : "Ohne feste zeitliche Eingrenzung"}</p>{result.data.confidence.date_span && <p>Inseratszeitraum: {result.data.confidence.date_span.oldest?.slice(0,10)} bis {result.data.confidence.date_span.newest?.slice(0,10)}</p>}{result.data.confidence.filters_applied?.length ? <p>Berücksichtigte Filter: {result.data.confidence.filters_applied.join(", ")}</p> : null}{result.data.confidence.filters_skipped?.length ? <p className="text-amber-800">Wegen geringer Datenmenge nicht verwendete Filter: {result.data.confidence.filters_skipped.join(", ")}</p> : null}<p className="text-sm text-muted-foreground">Die Preisspanne zeigt das mittlere Quartilsband der Vergleichsobjekte. Sie ist keine garantierte Verkaufspreisspanne.</p></CardContent></Card>
    </> : <p>Für diese Anfrage liegt noch kein vollständig bestätigtes Ergebnis vor.</p>}
    {input.success && <Card><CardHeader><CardTitle>Verwendete Objektdaten</CardTitle></CardHeader><CardContent className="space-y-2"><p>{input.data.street}, {input.data.postcode} {input.data.city}</p><p>{input.data.typ==="haus" ? "Haus" : "Wohnung"} · {input.data.square_meters} m² Wohnfläche · {input.data.rooms ?? "–"} Zimmer · Baujahr {input.data.year_of_construction ?? "–"}</p><p>Objektart: {propertyTypes.find(([id]) => id === input.data.property_type)?.[1] ?? "Keine zusätzliche Eingrenzung"}</p><p>Vermietung: {input.data.rented==null ? "Keine Eingrenzung" : input.data.rented ? "Vermietet" : "Bezugsfrei"}</p><p>Ausstattung: {Object.entries(input.data.features ?? {}).filter(([,v])=>v).map(([k])=>featureLabels[k as keyof typeof featureLabels]).join(", ") || "Keine zusätzliche Eingrenzung"}</p></CardContent></Card>}
    <p className="text-sm text-muted-foreground">Quelle: <a href="https://www.somantic.net/developers/docs" target="_blank" rel="noreferrer" className="underline">Somantic Immobilienbewertungs-API</a>. Automatisierte Markteinschätzung, kein Verkehrswertgutachten durch einen Sachverständigen. Der Bericht kann jederzeit erneut geöffnet werden, ohne einen weiteren Abruf auszulösen.</p>
  </article>;
}
