import { calculateMonthlyLeaseRentCents } from "../domain/rental";
import type {
  DemoDataset,
  LeasePaymentCandidate,
} from "../domain";

/**
 * Fictional, deterministic showcase data.
 *
 * Every entity is marked `isDemo: true`; names, IBANs, email addresses,
 * postcodes and addresses are intentionally non-real examples. This dataset
 * must never be presented as synchronized bank or production customer data.
 */
export const DEMO_DATA: DemoDataset = {
  mode: "demo",
  label: "Estate Brain – ausschließlich fiktive Demo-Daten",
  generatedForDate: "2026-07-31",
  organization: {
    id: "demo-org",
    name: "Demo-Portfolio Beispielverwaltung",
    isDemo: true,
    currency: "EUR",
    taxYearStartMonth: 1,
  },
  properties: [
    {
      id: "demo-property-alster",
      organizationId: "demo-org",
      name: "Demohaus Alsterblick",
      address: "Demoallee 12, 00000 Beispielstadt",
      propertyType: "apartment_building",
      purchaseDate: "2019-04-15",
      purchasePriceCents: 72_000_000,
      acquisitionCostsCents: 7_200_000,
      buildingShareCents: 57_600_000,
      landShareCents: 14_400_000,
      livingAreaSquareMeters: 239,
      currentMarketValueCents: 89_000_000,
      marketValueAsOf: "2026-06-30",
      isDemo: true,
    },
    {
      id: "demo-property-linden",
      organizationId: "demo-org",
      name: "Demo-Residenz Lindenhof",
      address: "Fiktivweg 7, 00000 Beispielstadt",
      propertyType: "condominium",
      purchaseDate: "2022-09-01",
      purchasePriceCents: 41_500_000,
      acquisitionCostsCents: 4_150_000,
      buildingShareCents: 33_200_000,
      landShareCents: 8_300_000,
      livingAreaSquareMeters: 152,
      currentMarketValueCents: 46_800_000,
      marketValueAsOf: "2026-06-30",
      isDemo: true,
    },
  ],
  units: [
    {
      id: "demo-unit-a1",
      propertyId: "demo-property-alster",
      label: "Wohnung EG links",
      floor: "EG",
      areaSquareMeters: 72,
      status: "occupied",
      isDemo: true,
    },
    {
      id: "demo-unit-a2",
      propertyId: "demo-property-alster",
      label: "Wohnung EG rechts",
      floor: "EG",
      areaSquareMeters: 64,
      status: "occupied",
      isDemo: true,
    },
    {
      id: "demo-unit-a3",
      propertyId: "demo-property-alster",
      label: "Wohnung 1. OG links",
      floor: "1. OG",
      areaSquareMeters: 55,
      status: "occupied",
      isDemo: true,
    },
    {
      id: "demo-unit-a4",
      propertyId: "demo-property-alster",
      label: "Wohnung 1. OG rechts",
      floor: "1. OG",
      areaSquareMeters: 48,
      status: "vacant",
      isDemo: true,
    },
    {
      id: "demo-unit-b1",
      propertyId: "demo-property-linden",
      label: "Wohnung 2. OG links",
      floor: "2. OG",
      areaSquareMeters: 82,
      status: "occupied",
      isDemo: true,
    },
    {
      id: "demo-unit-b2",
      propertyId: "demo-property-linden",
      label: "Wohnung 2. OG rechts",
      floor: "2. OG",
      areaSquareMeters: 70,
      status: "occupied",
      isDemo: true,
    },
  ],
  tenants: [
    {
      id: "demo-tenant-alpha",
      displayName: "Demo-Mieterin Alpha",
      email: "alpha@example.invalid",
      iban: "DE00 0000 0000 0000 0000 01",
      isDemo: true,
    },
    {
      id: "demo-tenant-beta",
      displayName: "Demo-Mieter Beta",
      email: "beta@example.invalid",
      iban: "DE00 0000 0000 0000 0000 02",
      isDemo: true,
    },
    {
      id: "demo-tenant-gamma",
      displayName: "Demo-Haushalt Gamma",
      email: "gamma@example.invalid",
      iban: "DE00 0000 0000 0000 0000 03",
      isDemo: true,
    },
    {
      id: "demo-tenant-delta",
      displayName: "Demo-Mieterin Delta",
      email: "delta@example.invalid",
      iban: "DE00 0000 0000 0000 0000 04",
      isDemo: true,
    },
    {
      id: "demo-tenant-epsilon",
      displayName: "Demo-Haushalt Epsilon",
      email: "epsilon@example.invalid",
      iban: "DE00 0000 0000 0000 0000 05",
      isDemo: true,
    },
  ],
  leases: [
    {
      id: "demo-lease-a1",
      unitId: "demo-unit-a1",
      tenantId: "demo-tenant-alpha",
      startDate: "2021-02-01",
      dueDay: 3,
      baseRentCents: 82_000,
      serviceChargeCents: 19_000,
      parkingRentCents: 4_000,
      otherRentCents: 0,
      depositCents: 246_000,
      paymentReference: "EB-A1-ALPHA",
      status: "active",
      isDemo: true,
    },
    {
      id: "demo-lease-a2",
      unitId: "demo-unit-a2",
      tenantId: "demo-tenant-beta",
      startDate: "2023-07-01",
      dueDay: 3,
      baseRentCents: 73_000,
      serviceChargeCents: 17_000,
      parkingRentCents: 0,
      otherRentCents: 0,
      depositCents: 219_000,
      paymentReference: "EB-A2-BETA",
      status: "active",
      isDemo: true,
    },
    {
      id: "demo-lease-a3",
      unitId: "demo-unit-a3",
      tenantId: "demo-tenant-gamma",
      startDate: "2020-11-01",
      dueDay: 3,
      baseRentCents: 64_000,
      serviceChargeCents: 15_000,
      parkingRentCents: 0,
      otherRentCents: 0,
      depositCents: 192_000,
      paymentReference: "EB-A3-GAMMA",
      status: "notice",
      endDate: "2026-10-31",
      isDemo: true,
    },
    {
      id: "demo-lease-b1",
      unitId: "demo-unit-b1",
      tenantId: "demo-tenant-delta",
      startDate: "2022-09-15",
      dueDay: 3,
      baseRentCents: 98_000,
      serviceChargeCents: 22_000,
      parkingRentCents: 5_000,
      otherRentCents: 0,
      depositCents: 294_000,
      paymentReference: "EB-B1-DELTA",
      status: "active",
      isDemo: true,
    },
    {
      id: "demo-lease-b2",
      unitId: "demo-unit-b2",
      tenantId: "demo-tenant-epsilon",
      startDate: "2024-01-01",
      dueDay: 3,
      baseRentCents: 87_000,
      serviceChargeCents: 20_000,
      parkingRentCents: 0,
      otherRentCents: 0,
      depositCents: 261_000,
      paymentReference: "EB-B2-EPSILON",
      status: "active",
      isDemo: true,
    },
  ],
  rentCharges: [
    {
      id: "demo-charge-jul-a1",
      leaseId: "demo-lease-a1",
      period: "2026-07",
      dueDate: "2026-07-03",
      targetAmountCents: 105_000,
      paidAmountCents: 105_000,
      status: "paid",
      isDemo: true,
    },
    {
      id: "demo-charge-jul-a2",
      leaseId: "demo-lease-a2",
      period: "2026-07",
      dueDate: "2026-07-03",
      targetAmountCents: 90_000,
      paidAmountCents: 0,
      status: "open",
      isDemo: true,
    },
    {
      id: "demo-charge-jul-a3",
      leaseId: "demo-lease-a3",
      period: "2026-07",
      dueDate: "2026-07-03",
      targetAmountCents: 79_000,
      paidAmountCents: 79_000,
      status: "paid",
      isDemo: true,
    },
    {
      id: "demo-charge-jul-b1",
      leaseId: "demo-lease-b1",
      period: "2026-07",
      dueDate: "2026-07-03",
      targetAmountCents: 125_000,
      paidAmountCents: 125_000,
      status: "paid",
      isDemo: true,
    },
    {
      id: "demo-charge-jul-b2",
      leaseId: "demo-lease-b2",
      period: "2026-07",
      dueDate: "2026-07-03",
      targetAmountCents: 107_000,
      paidAmountCents: 70_000,
      status: "partial",
      isDemo: true,
    },
    {
      id: "demo-charge-jun-a1",
      leaseId: "demo-lease-a1",
      period: "2026-06",
      dueDate: "2026-06-03",
      targetAmountCents: 105_000,
      paidAmountCents: 105_000,
      status: "paid",
      isDemo: true,
    },
  ],
  payments: [
    {
      id: "demo-payment-jul-a1",
      organizationId: "demo-org",
      bookingDate: "2026-07-02",
      amountCents: 105_000,
      senderName: "Demo-Mieterin Alpha",
      senderIban: "DE00 0000 0000 0000 0000 01",
      reference: "Miete 07/2026 EB-A1-ALPHA",
      leaseId: "demo-lease-a1",
      allocationStatus: "matched",
      isDemo: true,
    },
    {
      id: "demo-payment-jul-a3",
      organizationId: "demo-org",
      bookingDate: "2026-07-03",
      amountCents: 79_000,
      senderName: "Demo Haushalt Gamma",
      senderIban: "DE00 0000 0000 0000 0000 03",
      reference: "Juli EB-A3-GAMMA",
      leaseId: "demo-lease-a3",
      allocationStatus: "matched",
      isDemo: true,
    },
    {
      id: "demo-payment-jul-b1",
      organizationId: "demo-org",
      bookingDate: "2026-07-01",
      amountCents: 125_000,
      senderName: "Demo-Mieterin Delta",
      senderIban: "DE00 0000 0000 0000 0000 04",
      reference: "MIETE EB-B1-DELTA 07-2026",
      leaseId: "demo-lease-b1",
      allocationStatus: "matched",
      isDemo: true,
    },
    {
      id: "demo-payment-jul-b2-partial",
      organizationId: "demo-org",
      bookingDate: "2026-07-03",
      amountCents: 70_000,
      senderName: "Demo-Haushalt Epsilon",
      senderIban: "DE00 0000 0000 0000 0000 05",
      reference: "Teilzahlung EB-B2-EPSILON",
      leaseId: "demo-lease-b2",
      allocationStatus: "matched",
      isDemo: true,
    },
    {
      id: "demo-payment-jun-a1",
      organizationId: "demo-org",
      bookingDate: "2026-06-02",
      amountCents: 105_000,
      senderName: "Demo-Mieterin Alpha",
      senderIban: "DE00 0000 0000 0000 0000 01",
      reference: "Miete 06/2026 EB-A1-ALPHA",
      leaseId: "demo-lease-a1",
      allocationStatus: "matched",
      isDemo: true,
    },
    {
      id: "demo-payment-unmatched",
      organizationId: "demo-org",
      bookingDate: "2026-07-18",
      amountCents: 42_500,
      senderName: "Unbekanntes Demo-Konto",
      senderIban: "DE00 0000 0000 0000 0000 99",
      reference: "Umbuchung Demo",
      allocationStatus: "unmatched",
      isDemo: true,
    },
  ],
  expenses: [
    {
      id: "demo-expense-management",
      propertyId: "demo-property-alster",
      date: "2026-07-05",
      amountCents: 38_000,
      category: "property_management",
      description: "Demo-Hausverwaltung Juli",
      cashEffective: true,
      taxDeductible: true,
      apportionable: false,
      invoiceId: "demo-invoice-management",
      isDemo: true,
    },
    {
      id: "demo-expense-repair",
      propertyId: "demo-property-alster",
      unitId: "demo-unit-a2",
      date: "2026-07-11",
      amountCents: 124_900,
      category: "repair",
      description: "Fiktive Reparatur am Fenster",
      cashEffective: true,
      taxDeductible: true,
      apportionable: false,
      invoiceId: "demo-invoice-repair",
      isDemo: true,
    },
    {
      id: "demo-expense-insurance",
      propertyId: "demo-property-linden",
      date: "2026-07-15",
      amountCents: 21_500,
      category: "insurance",
      description: "Demo-Gebäudeversicherung",
      cashEffective: true,
      taxDeductible: true,
      apportionable: true,
      invoiceId: "demo-invoice-insurance",
      isDemo: true,
    },
    {
      id: "demo-expense-interest-alster",
      propertyId: "demo-property-alster",
      date: "2026-07-30",
      amountCents: 110_200,
      category: "loan_interest",
      description: "Demo-Zinsanteil Finanzierung A",
      cashEffective: true,
      taxDeductible: true,
      apportionable: false,
      isDemo: true,
    },
    {
      id: "demo-expense-principal-alster",
      propertyId: "demo-property-alster",
      date: "2026-07-30",
      amountCents: 84_800,
      category: "principal",
      description: "Demo-Tilgungsanteil Finanzierung A",
      cashEffective: true,
      taxDeductible: false,
      apportionable: false,
      isDemo: true,
    },
    {
      id: "demo-expense-capitalized",
      propertyId: "demo-property-linden",
      unitId: "demo-unit-b1",
      date: "2026-07-20",
      amountCents: 350_000,
      category: "capitalized",
      description: "Fiktive aktivierbare Modernisierung",
      cashEffective: true,
      taxDeductible: false,
      apportionable: false,
      invoiceId: "demo-invoice-modernization",
      isDemo: true,
    },
  ],
  invoices: [
    {
      id: "demo-invoice-management",
      propertyId: "demo-property-alster",
      invoiceDate: "2026-07-01",
      issuer: "Demo Hausservice GmbH (fiktiv)",
      grossAmountCents: 38_000,
      receiptStatus: "complete",
      paymentStatus: "paid",
      isDemo: true,
    },
    {
      id: "demo-invoice-repair",
      propertyId: "demo-property-alster",
      unitId: "demo-unit-a2",
      invoiceDate: "2026-07-10",
      issuer: "Beispiel Handwerk (fiktiv)",
      grossAmountCents: 124_900,
      receiptStatus: "review_required",
      paymentStatus: "paid",
      isDemo: true,
    },
    {
      id: "demo-invoice-insurance",
      propertyId: "demo-property-linden",
      invoiceDate: "2026-07-01",
      issuer: "Demo Versicherung (fiktiv)",
      grossAmountCents: 21_500,
      receiptStatus: "missing",
      paymentStatus: "paid",
      isDemo: true,
    },
    {
      id: "demo-invoice-modernization",
      propertyId: "demo-property-linden",
      unitId: "demo-unit-b1",
      invoiceDate: "2026-07-18",
      issuer: "Fiktivbau KG (fiktiv)",
      grossAmountCents: 350_000,
      receiptStatus: "unclear",
      paymentStatus: "open",
      isDemo: true,
    },
  ],
  loans: [
    {
      id: "demo-loan-alster",
      propertyId: "demo-property-alster",
      lender: "Demo Bank A (fiktiv)",
      loanNumberMasked: "DEMO-A-••1842",
      originalPrincipalCents: 50_000_000,
      currentBalanceCents: 41_320_000,
      annualInterestRate: 0.032,
      initialAnnualRepaymentRate: 0.02,
      monthlyPaymentCents: 195_000,
      fixedInterestEndDate: "2029-04-30",
      maturityDate: "2049-04-30",
      isDemo: true,
    },
    {
      id: "demo-loan-linden",
      propertyId: "demo-property-linden",
      lender: "Demo Bank B (fiktiv)",
      loanNumberMasked: "DEMO-B-••7310",
      originalPrincipalCents: 28_000_000,
      currentBalanceCents: 24_860_000,
      annualInterestRate: 0.0275,
      initialAnnualRepaymentRate: 0.025,
      monthlyPaymentCents: 122_500,
      fixedInterestEndDate: "2027-09-30",
      maturityDate: "2047-09-30",
      isDemo: true,
    },
  ],
  renovations: [
    {
      id: "demo-renovation-roof",
      propertyId: "demo-property-alster",
      category: "roof",
      description: "Fiktive Erneuerung der Dachabdichtung",
      condition: "poor",
      priority: "high",
      estimatedCostCents: 8_500_000,
      plannedDate: "2027-05-01",
      contingencyRate: 0.12,
      status: "planned",
      isDemo: true,
    },
    {
      id: "demo-renovation-heating",
      propertyId: "demo-property-linden",
      category: "heating",
      description: "Demo-Szenario für Heizungsmodernisierung",
      condition: "fair",
      priority: "medium",
      estimatedCostCents: 3_800_000,
      plannedDate: "2029-06-01",
      contingencyRate: 0.15,
      status: "offered",
      isDemo: true,
    },
    {
      id: "demo-renovation-interior",
      propertyId: "demo-property-alster",
      unitId: "demo-unit-a4",
      category: "interior",
      description: "Fiktive Herrichtung der leerstehenden Einheit",
      condition: "critical",
      priority: "urgent",
      estimatedCostCents: 1_250_000,
      plannedDate: "2026-09-15",
      contingencyRate: 0.1,
      status: "in_progress",
      isDemo: true,
    },
  ],
  tasks: [
    {
      id: "demo-task-payment",
      propertyId: "demo-property-alster",
      unitId: "demo-unit-a2",
      title: "Fehlende Demo-Mietzahlung prüfen",
      dueDate: "2026-08-02",
      priority: "high",
      status: "open",
      isDemo: true,
    },
    {
      id: "demo-task-invoice",
      propertyId: "demo-property-linden",
      title: "Fiktiven Versicherungsbeleg ergänzen",
      dueDate: "2026-08-05",
      priority: "medium",
      status: "open",
      isDemo: true,
    },
    {
      id: "demo-task-renovation",
      propertyId: "demo-property-alster",
      unitId: "demo-unit-a4",
      title: "Demo-Angebote für Innenausbau vergleichen",
      dueDate: "2026-08-12",
      priority: "high",
      status: "in_progress",
      isDemo: true,
    },
    {
      id: "demo-task-lease",
      propertyId: "demo-property-alster",
      unitId: "demo-unit-a3",
      title: "Auslaufendes Demo-Mietverhältnis vormerken",
      dueDate: "2026-09-15",
      priority: "medium",
      status: "open",
      isDemo: true,
    },
  ],
  messages: [
    {
      id: "demo-message-1",
      propertyId: "demo-property-alster",
      unitId: "demo-unit-a2",
      tenantId: "demo-tenant-beta",
      direction: "inbound",
      subject: "Fiktive Rückfrage zur Zahlung",
      body: "Dies ist eine Demo-Nachricht zur verspäteten Juli-Zahlung.",
      sentAt: "2026-07-29T09:15:00.000Z",
      read: false,
      isDemo: true,
    },
    {
      id: "demo-message-2",
      propertyId: "demo-property-alster",
      unitId: "demo-unit-a1",
      tenantId: "demo-tenant-alpha",
      direction: "outbound",
      subject: "Demo-Termin Innenausbau",
      body: "Fiktive Terminbestätigung für die Musteransicht.",
      sentAt: "2026-07-27T13:40:00.000Z",
      read: true,
      isDemo: true,
    },
    {
      id: "demo-message-3",
      propertyId: "demo-property-linden",
      unitId: "demo-unit-b2",
      tenantId: "demo-tenant-epsilon",
      direction: "inbound",
      subject: "Demo-Teilzahlung",
      body: "Der Restbetrag der fiktiven Juli-Miete folgt im Demo-Szenario.",
      sentAt: "2026-07-03T08:20:00.000Z",
      read: true,
      isDemo: true,
    },
    {
      id: "demo-message-4",
      propertyId: "demo-property-linden",
      unitId: "demo-unit-b1",
      tenantId: "demo-tenant-delta",
      direction: "outbound",
      subject: "Fiktive Wartungsankündigung",
      body: "Reine Demo-Kommunikation, keine reale Wartung.",
      sentAt: "2026-07-21T15:10:00.000Z",
      read: true,
      isDemo: true,
    },
  ],
  marketValuations: [
    {
      id: "demo-valuation-alster-2024",
      propertyId: "demo-property-alster",
      valueCents: 84_000_000,
      valuationDate: "2024-06-30",
      source: "manual_demo",
      uncertaintyNote: "Fiktiver manueller Demowert ohne Marktgutachten.",
      isDemo: true,
    },
    {
      id: "demo-valuation-alster-2026",
      propertyId: "demo-property-alster",
      valueCents: 89_000_000,
      valuationDate: "2026-06-30",
      source: "manual_demo",
      uncertaintyNote: "Fiktiver manueller Demowert ohne Marktgutachten.",
      isDemo: true,
    },
    {
      id: "demo-valuation-linden-2024",
      propertyId: "demo-property-linden",
      valueCents: 44_200_000,
      valuationDate: "2024-06-30",
      source: "manual_demo",
      uncertaintyNote: "Fiktiver manueller Demowert ohne Marktgutachten.",
      isDemo: true,
    },
    {
      id: "demo-valuation-linden-2026",
      propertyId: "demo-property-linden",
      valueCents: 46_800_000,
      valuationDate: "2026-06-30",
      source: "manual_demo",
      uncertaintyNote: "Fiktiver manueller Demowert ohne Marktgutachten.",
      isDemo: true,
    },
  ],
  taxAssumption: {
    organizationId: "demo-org",
    taxYear: 2026,
    marginalTaxRate: 0.3,
    lossOffsetAllowed: true,
    enabled: true,
    note: "Fiktive, editierbare Demo-Annahme; keine Steuerberatung.",
    isDemo: true,
  },
};

/**
 * Produces payment candidates from demo records without mutating the dataset.
 */
export function createDemoPaymentCandidates(
  dueDate: string = "2026-07-03",
): LeasePaymentCandidate[] {
  return DEMO_DATA.leases.map((lease) => {
    const unit = DEMO_DATA.units.find((item) => item.id === lease.unitId);
    const property = DEMO_DATA.properties.find(
      (item) => item.id === unit?.propertyId,
    );
    const tenant = DEMO_DATA.tenants.find(
      (item) => item.id === lease.tenantId,
    );
    if (!unit || !property || !tenant) {
      throw new Error(
        `Inkonsistente Demo-Referenz im Mietverhältnis ${lease.id}.`,
      );
    }
    const expectedAmountCents = calculateMonthlyLeaseRentCents({
      baseRentCents: lease.baseRentCents,
      serviceChargeCents: lease.serviceChargeCents,
      parkingRentCents: lease.parkingRentCents,
      otherRentCents: lease.otherRentCents,
    });

    return {
      leaseId: lease.id,
      propertyId: property.id,
      unitId: unit.id,
      propertyLabel: property.name,
      unitLabel: unit.label,
      expectedAmountCents,
      outstandingAmountCents: expectedAmountCents,
      dueDate,
      tenantName: tenant.displayName,
      tenantIban: tenant.iban,
      paymentReference: lease.paymentReference,
      eligible: lease.status !== "ended",
    };
  });
}

export const DEMO_PAYMENT_MATCH_CANDIDATES =
  createDemoPaymentCandidates();
