-- Rent-claim totals and payment status are projections of confirmed payments.
-- Claims are generated by the validated monthly RPC, and their derived fields
-- are refreshed by the rent-payment trigger. Browser clients therefore do not
-- need direct INSERT or UPDATE access to the table.

revoke insert, update on public.rent_claims from authenticated;

drop policy if exists rent_claims_insert_bookkeeping
  on public.rent_claims;
drop policy if exists rent_claims_update_bookkeeping
  on public.rent_claims;

comment on function public.generate_monthly_rent_claims(uuid, date) is
  'Validated browser write path for monthly claims; direct authenticated INSERT and UPDATE are disabled.';
comment on function private.refresh_rent_claim_totals() is
  'Maintains paid_cents and status from confirmed rent payments; browser clients cannot alter these projections directly.';
